# Generated by Django 4.1.5 on 2023-05-16 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Myprofile',
            fields=[
                ('cmp_nm', models.CharField(db_column='CMP_NM', max_length=10)),
                ('designation', models.CharField(db_column='DESIGNATION', max_length=10)),
                ('rspbty', models.CharField(blank=True, db_column='RSPBTY', max_length=50, null=True)),
                ('st_dt', models.DateField(blank=True, db_column='ST_DT', null=True)),
                ('ed_dt', models.DateField(blank=True, db_column='ED_DT', null=True)),
                ('M', models.IntegerField(db_column='EMP_ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'myprofile',
                'managed': False,
            },
        ),
    ]
