# Generated by Django 4.1.5 on 2023-05-16 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_tech'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tech',
            options={'managed': True},
        ),
    ]
