# Generated by Django 4.1.5 on 2023-05-16 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_tech_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tech',
            name='company',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tech',
            name='company2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
